### ISSUE TITLE
EndToEndTransactionTest#attach_Error_Rollback has uncaught promise rejection

### ISSUE THREAD

**Issue by arthurhsu** [arthurhsu/lovefield-ts#12]
On both Chrome and NodeJS mocha. The code actually has proper try-catch, however the rejected promise is still deemed as unhandled.

The original code uses thenCatch(), which is not provided in ES6. Either async function or plain Promise still result in unhandled promise rejection, not sure if that's a TypeScript problem or not.

**Comment by freshp86** [comment]
FYI  `goog.Promise#thenCatch()` exists now as `Promise#finally()`, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally.

**Comment by arthurhsu** [comment]
Pretty sure it's TypeScript problem now. Typescript uses the following awaiter:

```javascript
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
```

When the value is in the rejected state, it calls the generator to throw it, and we have no way to set the result.done to end that throw loop.

**Comment by arthurhsu** [comment]
Found the root cause:
https://github.com/google/lovefield/blob/master/lib/proc/transaction_task.js#L148

Original code uses CancellationError, which has a side effect in Closure that can nicely cancel the promise. This is not provided by native Promise that used in the Typescript port.

Current implementation uses
https://github.com/google/lovefield/blob/master/lib/proc/transaction_task.js#L148

which will do exactly the opposite as said in its comment above. Can't really blame freshp86@ because when he wrote that code, Promise.cancel is still an active proposal and not dead yet (and it's freaking dead now so we need to think another way to overcome).
